### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by lensvol**
"steaming" -> "streaming"

### CODE REVIEW

**Comment by lensvol** [comment]
As it is duplicated by https://github.com/RazrFalcon/pico-args/pull/55

**Comment by RazrFalcon** [comment]
Can you reopen it please?

**Comment by lensvol** [comment]
@RazrFalcon As you command.

**Comment by RazrFalcon** [comment]
Thanks!

**Comment by lensvol** [comment]
My pleasure!

**Pull request merged**
