### PR TITLE
Add combined-flag feature

### LINKED ISSUE #34: Combined flags question
Hey I had a question about combined flags -- is this something that you don't want to support because of the minimalist principles of this library, or just something that you haven't implemented, but would be open to?

### PR DESCRIPTION
**Pull request by alexwennerberg**
Close #34 

The README references repeated flags ("-vvv") -- this was possible via the previous and current API: just by matching `contains("-v")`, `contains("-vv")`, `contains("-vvv")`, etc -- my change doesn't impact this, it only adds combined flags.

This feature is mutually exclusive with short-space-opt, but it looks like enforcing exclusive build features in cargo is a WIP: https://github.com/rust-lang/cargo/issues/2980 -- let me know how you think we should handle this. It doesn't break the build pipeline currently, but I could write some tests such that it does, bc it definitely would cause buggy behavior

Also I have rustfmt running with the default settings and it reformatted your code (but I didn't commit these changes) -- are you using different settings for rustfmt or is something wrong with my dev environment?

Let me know what you think and if you have any feedback!

### CODE REVIEW

**Comment by alexwennerberg** [comment]
There are no test cases "long" short keys, e.g. "-version" -- this is technically allowed by this library, should it be banned for all features, not just combined-flag?

**Comment by alexwennerberg** [comment]
Here's an example test case for a conflict with `short-space-opt`:

```rust
#[cfg(all(feature = "short-space-opt", feature = "combined-flags"))]
#[test]
fn long_shortflag() {
    let mut args = Arguments::from_vec(to_vec(&["-wab -ca"]));
    assert!(args.contains("-a"));
    assert!(args.contains("-c"));
    let value: Option<String> = args.opt_value_from_str(["-w", "--width"]).unwrap();
    assert_eq!(&value.unwrap(), "ab")
}
```

**Comment by RazrFalcon** [comment]
Hi! Sorry for a delay.

>This feature is mutually exclusive with short-space-opt

You can use [compile_error!](https://doc.rust-lang.org/stable/std/macro.compile_error.html) for this. And mention this in the docs/readme.

As for tests, does this works?

```rust
let mut args = Arguments::from_vec(to_vec(&["-aa"]));
assert_eq!(args.contains("-a"), true);
assert_eq!(args.contains("-a"), true);
assert_eq!(args.contains("-a"), false);
```

Can we access value after short flag?

```rust
let mut args = Arguments::from_vec(to_vec(&["-aa a"])); // ???
```

What about numerals and misleading commands?

```rust
let mut args = Arguments::from_vec(to_vec(&["-j1"])); // ???
```

Can it properly process non-ASCII/non-Latin1 encodings?

```rust
let mut args = Arguments::from_vec(to_vec(&["-😀"])); // ???
```

What about:

```rust
let mut args = Arguments::from_vec(to_vec(&["-abc"]));
assert!(args.contains("-b"));
assert!(args.contains("-ac")); // this would be `true`, but it actually should be `false`
```

PS: args parsing is surprisingly hard...

**Comment by RazrFalcon** [comment]
>There are no test cases "long" short keys, e.g. "-version" 

This should be banned.

**Comment by RazrFalcon** [comment]
>are you using different settings for rustfmt or is something wrong with my dev environment?

I'm not using it at all. The project is tiny and should be just fine without autoformatting.

**Comment by RazrFalcon** [comment]
>instead of doing the parsing when creating the Arguments objects

What do you mean by that? pico-args designed to be as simple as possible and as small as possible. This is the main goal.

**Comment by alexwennerberg** [comment]
> Hi! Sorry for a delay.

No problem!
> 
> > This feature is mutually exclusive with short-space-opt
> 
> You can use [compile_error!](https://doc.rust-lang.org/stable/std/macro.compile_error.html) for this. And mention this in the docs/readme.
> 
> As for tests, does this works?
> 
> ```rust
> let mut args = Arguments::from_vec(to_vec(&["-aa"]));
> assert_eq!(args.contains("-a"), true);
> assert_eq!(args.contains("-a"), true);
> assert_eq!(args.contains("-a"), false);
> ```

This should work.

> 
> Can we access value after short flag?
> 
> ```rust
> let mut args = Arguments::from_vec(to_vec(&["-aa a"])); // ???
> ```

The parser I wrote modifies the string in Arguments, so after calling contains("-a") twice, this will be `&["a"]`

>
> 
> What about numerals and misleading commands?
> 
> ```rust
> let mut args = Arguments::from_vec(to_vec(&["-j1"])); // ???
> ```
> 
> Can it properly process non-ASCII/non-Latin1 encodings?
> 
> ```rust
> let mut args = Arguments::from_vec(to_vec(&["-😀"])); // ???
> ```

I see no reason why not, I use Rust's `char` and `str` with no other constraints on utf8

> 
> What about:
> 
> ```rust
> let mut args = Arguments::from_vec(to_vec(&["-abc"]));
> assert!(args.contains("-b"));
> assert!(args.contains("-ac")); // this would be `true`, but it actually should be `false`
> ```

The second would be banned by https://github.com/RazrFalcon/pico-args/pull/35#issuecomment-827387050
> 
> PS: args parsing is surprisingly hard...

Tell me about it lol

**Comment by alexwennerberg** [comment]
> > instead of doing the parsing when creating the Arguments objects
> 
> What do you mean by that? pico-args designed to be as simple as possible and as small as possible. This is the main goal.

I only briefly had a chance to look at this part of the code, but it looks like the options like the compiler flags like `eq-separator` modify how the options/flags in Arguments are read. What I'm suggesting is that it should modify how the Arguments struct is constructed: so that `-a=1` be stored in Arguments as `&["-a", "1"]` instead of `&["-a=1"]` -- do you see any problems with this?

PS Have you considered using a trait instead of a struct to represent Arguments? This would prevent having to reference `self.0`

**Comment by RazrFalcon** [comment]
>so that -a=1 be stored in Arguments as &["-a", "1"] instead of &["-a=1"] -- do you see any problems with this

Are you suggesting that we should split `=` args beforehand? I haven't thought about it. It would greatly simplify parsing.
But I'm not sure it would work for `-Kvalue`.

>Have you considered using a trait instead of a struct to represent Arguments?

A trait that would be implemented for `Vec<Vec<OsString>>`? I don't think it would be user-friendly.

**Comment by alexwennerberg** [comment]
Are there any outstanding issues for this PR? Here’s what I see —

1. Making the 1 character shortflag limit apply to all compiler flags not just this one
2. Update readme to mention that if you are using shortflags and have one of the flags i mentioned above enabled, you should call them after any key/value options to prevent ambiguity

Alex

**Comment by RazrFalcon** [comment]
3. Add more tests. Specifically the first and the last from my comment.

**Comment by alexwennerberg** [comment]
Sounds good. I might have time after work today or tomorrow to finish that up 👍

Alex

**Comment by alexwennerberg** [comment]
OK, should have resolved all the issues, except that there's no way to make the last test you mentioned pass, since it violates the constraint I added in https://github.com/RazrFalcon/pico-args/pull/35#issuecomment-827387050 and will trigger a compile error

Let me know if you have any other feedback!

**Comment by RazrFalcon** [comment]
Thanks! Looks good.

**Pull request merged**
