### PR TITLE
Add an example of using `--` with `from_vec`

### PR DESCRIPTION
**Pull request by jyn514**
Closes https://github.com/RazrFalcon/pico-args/issues/25.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
I was thinking about a standalone example. Like the `examples/app.rs`

**Comment by jyn514** [comment]
Hmm, I don't think standalone examples are as easy to find on docs.rs, you have to look in the `source` page. Maybe it could be both a standalone example and use `include_doc!` so it shows up in the main documentation?

**Comment by RazrFalcon** [comment]
Don't worry. People will find it.

**Comment by jyn514** [comment]
Ok, I switched this to use an example and mentioned it in the docs for `from_vec`.

**Comment by RazrFalcon** [comment]
Thanks.

**Pull request merged**
